### ISSUE TITLE
Convert snakecase table keys into lower camel case in the generated dart models

### ISSUE THREAD

**Issue by Yoeri-z** [utopicnarwhal/pocketbase_utils#2]
The naming convention for sql and pocketbase is snakecase, currently the dart classes match the table rows one to one so the dart property is also in snake case. The naming convention for dart (and my entire codebase) is lower camel case. Maybe it would be a nice feature to automatically convert snake case keys to lower camel case in the model generation or at least add an option to enable it in the pubspec?

I believe json_serializable even has support for this

**Comment by utopicnarwhal** [comment]
Hi, can you try my feature branch with the support for your snake_case convention by referencing the commit in your pubspec.yaml file:
```yaml
  # pocketbase_utils: ^0.1.0 <- you have it already, so you can comment it for now
  pocketbase_utils:
    git:
      url: https://github.com/utopicnarwhal/pocketbase_utils
      ref: 2017546ff1a8c6a1ef25cd73e12c5872d8e8491f
```
And then run the `dart run pocketbase_utils:generate` command and the `dart run build_runner build --delete-conflicting-outputs` command.

Please, let me know how it went for you so I'll create a new release of the package after your confirmation.
