### ISSUE TITLE
Support GeoPoint type

### ISSUE THREAD

**Issue by chabad360** [utopicnarwhal/pocketbase_utils#3]
Pocketbase now has support for GeoPoint fields (basically just an object with Lat and Long), if pocketbase_utils could get support for that, that would be awesome.

**Comment by utopicnarwhal** [comment]
Hi @chabad360 , can you try my code referencing the commit in your pubspec.yaml file:
```yaml
dev_dependencies:
  ...
  # pocketbase_utils: ^0.1.1 <- you have it already, so you can comment it for now
  pocketbase_utils:
    git:
      url: https://github.com/utopicnarwhal/pocketbase_utils
      ref: ee2fb36740a9c8dd2e418ff2236570b4793577fb
```
And then run the `dart run pocketbase_utils:generate` command and the `dart run build_runner build --delete-conflicting-outputs` command.

Please, let me know how it went for you so I'll create a new release of the package after your confirmation.
