### ISSUE TITLE
Username and Email are not always available

### ISSUE THREAD

**Issue by chabad360** [utopicnarwhal/pocketbase_utils#4]
Pocketbase no longer includes a `username` field by default in the Users table. Additionally, Pocketbase also has a new field `emailVisibility` which when not set, will hide a user's email from views and lists by other users. Which effectively means that the `email` field should not be required either (unless perhaps, the `emailVisibilty` is set as NonFalsey).

**Comment by utopicnarwhal** [comment]
Hello again @chabad360 , you can try my feature branch referencing the commit in your pubspec.yaml file:

```yaml
dev_dependencies:
  ...
  # pocketbase_utils: ^0.1.2 <- you have it already, so you can comment it for now
  pocketbase_utils:
    git:
      url: https://github.com/utopicnarwhal/pocketbase_utils
      ref: 26698192f447229d0afc7a4f274066bf01d61d6d
```

And don't forget to run the `dart run pocketbase_utils:generate` command and the `dart run build_runner build --delete-conflicting-outputs` commands.
